### ISSUE TITLE
Aircraft shows up as transmitting, when it's not even on my frequency

### ISSUE THREAD

**Issue by h-okon** [chembergj/RDF#2]
As in title - aircraft is showing up as a transmiting one, when it is not even connected to my frequency 
[](url)
![RjyIbO8](https://user-images.githubusercontent.com/42499717/63226973-a580e100-c1e1-11e9-9f59-bffb9f167d47.png)

**Comment by chembergj** [comment]
Since the plugin has been rewritten for the new Audio For Vatsim, I will close this issue, as it is probably no longer relevant. Should you experience the issue again, please reopen this issue.
