### ISSUE TITLE
Can't highlight if OBS

### ISSUE THREAD

**Issue by sparrowhe** [chembergj/RDF#6]
I cant use this plugin. I was logged with obs mode. no active any freq.
![image](https://user-images.githubusercontent.com/26871028/104684124-4bb47b80-5733-11eb-9744-bb9fb0d8dbcf.png)
No highlight when any aircraft talking.

**Comment by chembergj** [comment]
Unfortunately, the issue cannot be solved in the plugin. The reason seems to be, that Audio for VATSIM do not pass messages on to my plugin regarding voice comm when the user is logged in as OBS, as it does when logged in as controller. Therefore, RDF has no information to draw the circles.
